name: ESPHome tadiran widi Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ESPHome
      run: pip install esphome

    - name: Build ESPHome tadiran wifi firmware
      run: esphome compile examples/Gekkehenkie11.yaml
