name: ESPHome tadiran wifi Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install ESPHome
      run: pip install esphome

    - name: Build ESPHome tadiran wifi firmware
      run: esphome compile build/tadiran.yaml
      
    - name: Archive firmware binaries and ELF files
      uses: actions/upload-artifact@v4
      with:
        name: esphome-artifacts
        path: |
          ./build/.esphome/build/gree/.pioenvs/gree/firmware.*.bin
